# Generated by Django 4.2.8 on 2023-12-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("receipts", "0002_alter_receipt_purchase_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="receipt",
            name="updated_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name="receipt",
            index=models.Index(
                fields=["store_name", "purchase_date"], name="store_name_index"
            ),
        ),
        migrations.AddIndex(
            model_name="receipt",
            index=models.Index(fields=["purchase_date"], name="purchase_date_index"),
        ),
        migrations.AddIndex(
            model_name="receipt",
            index=models.Index(fields=["total_ammount"], name="total_ammount_index"),
        ),
        migrations.AddConstraint(
            model_name="receipt",
            constraint=models.UniqueConstraint(
                fields=("store_name", "purchase_date"), name="unique_user_receipt"
            ),
        ),
    ]
