# Generated by Django 4.2.8 on 2023-12-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("receipts", "0003_receipt_created_date_receipt_updated_date_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="receipt",
            name="unique_user_receipt",
        ),
        migrations.AddConstraint(
            model_name="receipt",
            constraint=models.UniqueConstraint(
                fields=("user", "store_name", "purchase_date"),
                name="unique_user_receipt",
            ),
        ),
    ]
