# Generated by Django 4.2.3 on 2023-12-16 05:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("receipts", "0004_remove_receipt_unique_user_receipt_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="receipt",
            name="store_name_index",
        ),
        migrations.RemoveIndex(
            model_name="receipt",
            name="purchase_date_index",
        ),
        migrations.RemoveIndex(
            model_name="receipt",
            name="total_ammount_index",
        ),
        migrations.AddIndex(
            model_name="receipt",
            index=models.Index(
                fields=["user", "store_name", "purchase_date"], name="store_name_index"
            ),
        ),
        migrations.AddIndex(
            model_name="receipt",
            index=models.Index(
                fields=["user", "purchase_date"], name="purchase_date_index"
            ),
        ),
        migrations.AddIndex(
            model_name="receipt",
            index=models.Index(
                fields=["user", "total_ammount"], name="total_ammount_index"
            ),
        ),
    ]
